// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-H292N3d6EApFuPL5Uk813ebqpdpThA',
    appId: '1:11920817576:web:f19ca8a0e14f6acf35719d',
    messagingSenderId: '11920817576',
    projectId: 'opensource-team3-refrigerator',
    authDomain: 'opensource-team3-refrigerator.firebaseapp.com',
    storageBucket: 'opensource-team3-refrigerator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-KQ9aaZE5aHpAFd_0sPoEgpaG32jAkk',
    appId: '1:11920817576:android:2217c2757f70ce4335719d',
    messagingSenderId: '11920817576',
    projectId: 'opensource-team3-refrigerator',
    storageBucket: 'opensource-team3-refrigerator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5nehWQEBtj2f4qng8w0B4G8vxzpYMB_I',
    appId: '1:11920817576:ios:e3beb88ed664fdcd35719d',
    messagingSenderId: '11920817576',
    projectId: 'opensource-team3-refrigerator',
    storageBucket: 'opensource-team3-refrigerator.appspot.com',
    iosClientId: '11920817576-4vo42t1jug5npr7qip3rvubp54dcjpa1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5nehWQEBtj2f4qng8w0B4G8vxzpYMB_I',
    appId: '1:11920817576:ios:25d0aab71e0b374a35719d',
    messagingSenderId: '11920817576',
    projectId: 'opensource-team3-refrigerator',
    storageBucket: 'opensource-team3-refrigerator.appspot.com',
    iosClientId: '11920817576-ia3qm5g6t40feooo7tr3m1882odit2pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
